//! `rein.lock` version pinning.
//!
//! Auto-generated lockfile that pins tool versions and SHA-256 hashes
//! for reproducible builds.

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::fs;
use std::io;
use std::path::Path;

#[cfg(test)]
mod tests;

/// The lockfile format.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LockFile {
    /// Lockfile schema version.
    pub version: u32,
    /// Pinned tools with their versions and hashes.
    pub tools: BTreeMap<String, ToolPin>,
    /// Pinned models with their versions.
    pub models: BTreeMap<String, ModelPin>,
}

/// A pinned tool entry.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ToolPin {
    pub version: String,
    /// SHA-256 hash of the tool binary or config.
    pub sha256: String,
    /// Source URL or registry reference.
    pub source: Option<String>,
}

/// A pinned model entry.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ModelPin {
    pub version: String,
    pub provider: String,
}

/// Error type for lockfile operations.
#[derive(Debug)]
pub enum LockError {
    Io(io::Error),
    Toml(toml::de::Error),
    TomlSer(toml::ser::Error),
}

impl std::fmt::Display for LockError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Io(e) => write!(f, "lockfile I/O error: {e}"),
            Self::Toml(e) => write!(f, "lockfile parse error: {e}"),
            Self::TomlSer(e) => write!(f, "lockfile serialization error: {e}"),
        }
    }
}

impl std::error::Error for LockError {}

impl From<io::Error> for LockError {
    fn from(e: io::Error) -> Self {
        Self::Io(e)
    }
}

impl LockFile {
    /// Current lockfile version.
    pub const VERSION: u32 = 1;

    /// Create a new empty lockfile.
    pub fn new() -> Self {
        Self {
            version: Self::VERSION,
            tools: BTreeMap::new(),
            models: BTreeMap::new(),
        }
    }

    /// Load a lockfile from disk.
    pub fn load(path: &Path) -> Result<Self, LockError> {
        let content = fs::read_to_string(path)?;
        toml::from_str(&content).map_err(LockError::Toml)
    }

    /// Save the lockfile to disk.
    pub fn save(&self, path: &Path) -> Result<(), LockError> {
        let header = "# Auto-generated by rein. Do not edit.\n\n";
        let content = toml::to_string_pretty(self).map_err(LockError::TomlSer)?;
        fs::write(path, format!("{header}{content}"))?;
        Ok(())
    }

    /// Pin a tool with its version and SHA-256 hash.
    pub fn pin_tool(
        &mut self,
        name: impl Into<String>,
        version: impl Into<String>,
        sha256: impl Into<String>,
    ) {
        self.tools.insert(
            name.into(),
            ToolPin {
                version: version.into(),
                sha256: sha256.into(),
                source: None,
            },
        );
    }

    /// Pin a model with its version and provider.
    pub fn pin_model(
        &mut self,
        name: impl Into<String>,
        version: impl Into<String>,
        provider: impl Into<String>,
    ) {
        self.models.insert(
            name.into(),
            ModelPin {
                version: version.into(),
                provider: provider.into(),
            },
        );
    }

    /// Verify a tool's hash against the pinned value.
    pub fn verify_tool(&self, name: &str, content: &[u8]) -> Option<bool> {
        self.tools.get(name).map(|pin| {
            let hash = compute_sha256(content);
            hash == pin.sha256
        })
    }
}

impl Default for LockFile {
    fn default() -> Self {
        Self::new()
    }
}

/// Compute the SHA-256 hex digest of data.
pub fn compute_sha256(data: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(data);
    format!("{:x}", hasher.finalize())
}
