use super::*;
use tempfile::TempDir;

#[test]
fn new_lockfile_is_empty() {
    let lock = LockFile::new();
    assert_eq!(lock.version, LockFile::VERSION);
    assert!(lock.tools.is_empty());
    assert!(lock.models.is_empty());
}

#[test]
fn pin_and_verify_tool() {
    let mut lock = LockFile::new();
    let data = b"tool binary content";
    let hash = compute_sha256(data);
    lock.pin_tool("search", "1.0.0", &hash);

    assert_eq!(lock.verify_tool("search", data), Some(true));
    assert_eq!(lock.verify_tool("search", b"modified"), Some(false));
    assert_eq!(lock.verify_tool("unknown", data), None);
}

#[test]
fn pin_model() {
    let mut lock = LockFile::new();
    lock.pin_model("gpt-4o", "2024-05-13", "openai");
    let pin = &lock.models["gpt-4o"];
    assert_eq!(pin.version, "2024-05-13");
    assert_eq!(pin.provider, "openai");
}

#[test]
fn save_and_load() {
    let tmp = TempDir::new().unwrap();
    let path = tmp.path().join("rein.lock");

    let mut lock = LockFile::new();
    lock.pin_tool("search", "1.0.0", "abc123");
    lock.pin_model("gpt-4o", "2024-05-13", "openai");
    lock.save(&path).unwrap();

    let loaded = LockFile::load(&path).unwrap();
    assert_eq!(loaded, lock);
}

#[test]
fn sha256_is_deterministic() {
    let a = compute_sha256(b"hello");
    let b = compute_sha256(b"hello");
    assert_eq!(a, b);
    assert_ne!(a, compute_sha256(b"world"));
}

#[test]
fn lockfile_header_preserved() {
    let tmp = TempDir::new().unwrap();
    let path = tmp.path().join("rein.lock");
    let lock = LockFile::new();
    lock.save(&path).unwrap();

    let content = std::fs::read_to_string(&path).unwrap();
    assert!(content.starts_with("# Auto-generated by rein."));
}
